name: Call E2E tests

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
    branches:
      - master

jobs:
  e2e-pull-request-tests:
    name: Call E2E tests on pull request
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'grmmvv')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Call python
        run: python --version
