name: Call E2E tests

on:
  push:
    branches:
      - dev

env:
  TEAMCITY_TOKEN: ${{ secrets.TEAMCITY_TOKEN }}

jobs:
  e2e-push-request-tests:
    name: Call E2E tests on push
    runs-on: ubuntu-latest
    steps:
      - name: Curl TeamCity
        env:
          BUILD_ID: "SuShi_TestAutomation_Delme"
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
