name: Call E2E tests

on:
  push:
    branches:
      - dev


jobs:
  e2e-push-request-tests:
    name: Call E2E tests on push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Call python
        run: python --version
