name: Python package

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]


jobs:
  build:
    name: Test job
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'grmmvv')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Call python
        run: python --version
